[licenses]
confidence-threshold = 0.8
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "Apache-2.0 WITH LLVM-exception", "MPL-2.0"]

[[licenses.exceptions]]
allow = ["GPL-3.0-only"]
name = "groundsplit"

[advisories]
ignore = [
  { id = "RUSTSEC-2025-0075", reason = "rust-unic is unmaintained, but piet relies on it.." },
  { id = "RUSTSEC-2025-0080", reason = "rust-unic is unmaintained, but piet relies on it.." },
  { id = "RUSTSEC-2025-0081", reason = "rust-unic is unmaintained, but piet relies on it.." },
  { id = "RUSTSEC-2025-0083", reason = "rust-unic is unmaintained, but piet relies on it.." },
  { id = "RUSTSEC-2025-0096", reason = "rust-unic is unmaintained, but piet relies on it.." },
  { id = "RUSTSEC-2025-0098", reason = "rust-unic is unmaintained, but piet relies on it.." },
]
