name: release
on:
  push:
    tags:
      - "*"

jobs:
  publish-github:
    name: publish for ${{ matrix.build.OS }} (${{ matrix.build.TARGET }})
    runs-on: ${{ matrix.build.OS }}
    permissions:
      contents: write # for publishing release
    strategy:
      fail-fast: false
      matrix:
        build:
          - { OS: ubuntu-latest, TARGET: x86_64-unknown-linux-gnu }
          - { OS: ubuntu-latest, TARGET: x86_64-unknown-linux-musl }
          - { OS: ubuntu-latest, TARGET: aarch64-unknown-linux-gnu }
          - { OS: ubuntu-latest, TARGET: riscv64gc-unknown-linux-gnu }
          - { OS: ubuntu-latest, TARGET: i686-unknown-linux-gnu }
          - { OS: ubuntu-latest, TARGET: i686-unknown-linux-musl }
          - { OS: ubuntu-latest, TARGET: aarch64-unknown-linux-musl }
          - { OS: ubuntu-latest, TARGET: armv5te-unknown-linux-gnueabi }
          - { OS: ubuntu-latest, TARGET: armv7-unknown-linux-gnueabihf }
          - { OS: ubuntu-latest, TARGET: arm-unknown-linux-gnueabi }
          - { OS: ubuntu-latest, TARGET: arm-unknown-linux-gnueabihf }
          - { OS: ubuntu-latest, TARGET: powerpc64le-unknown-linux-gnu }
          - { OS: windows-latest, TARGET: x86_64-pc-windows-msvc }
          - { OS: macos-latest, TARGET: x86_64-apple-darwin }
          - { OS: macos-latest, TARGET: aarch64-apple-darwin }
    steps:
      - uses: actions/checkout@v7

      - name: set release version and CLI name
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "CLI_NAME=$(basename $PWD)" >> $GITHUB_ENV

      - name: install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.build.TARGET }}

      - name: cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.build.TARGET }}

      # TODO: only on linux
      - name: install libs
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev libcairo2-dev libpango1.0-dev

      - name: build
        run: cargo build --release --locked --target ${{ matrix.build.TARGET }}

      - name: prepare release assets
        shell: bash
        run: |
          mkdir -p ${{env.CLI_NAME}}-${{env.RELEASE_VERSION}}
          cp {LICENSE,README.md,CHANGELOG.md} ${{env.CLI_NAME}}-${{env.RELEASE_VERSION}}/
          if [ "${{ matrix.build.OS }}" = "windows-latest" ]; then
            cp target/${{ matrix.build.TARGET }}/release/${{env.CLI_NAME}}.exe ${{env.CLI_NAME}}-${{env.RELEASE_VERSION}}/
          else
            cp target/${{ matrix.build.TARGET }}/release/${{env.CLI_NAME}} ${{env.CLI_NAME}}-${{env.RELEASE_VERSION}}/
          fi

      - name: create release artifacts
        shell: bash
        run: |
          if [ "${{ matrix.build.OS }}" = "windows-latest" ]; then
            7z a -tzip "${{env.CLI_NAME}}-${{ matrix.build.TARGET }}.zip" ${{env.CLI_NAME}}-${{ env.RELEASE_VERSION }}/
          else
            tar -czvf ${{env.CLI_NAME}}-${{ matrix.build.TARGET }}.tar.gz ${{env.CLI_NAME}}-${{ env.RELEASE_VERSION }}/
            shasum -a 512 ${{env.CLI_NAME}}-${{ matrix.build.TARGET }}.tar.gz > ${{env.CLI_NAME}}-${{ matrix.build.TARGET }}.tar.gz.sha512
          fi

      - name: publish release
        uses: svenstaro/upload-release-action@v2
        with:
          file: "*-${{ matrix.build.TARGET }}*"
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: v${{ env.RELEASE_VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  publish-crates-io:
    name: Publish on crates.io
    needs: publish-github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo publish --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
